

  theme                  : "jekyll-theme-hacker"
# remote_theme           : "mmistakes/minimal-mistakes"
#minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "m4nd4rk"
#title_separator          : "-"
name                     : "m4nd4rk"
description              : "Just another personal blog"
url                      : "https://m4nd4rk.github.io"
breadcrumbs              : true # true, false (default)
words_per_minute         : 200
