

  theme                  : "jekyll-theme-hacker"
# remote_theme           : "mmistakes/minimal-mistakes"
#minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "m4nd4rk"
#title_separator          : "-"
name                     : "m4nd4rk"
description              : "Just another personal blog"
url                      : "https://m4nd4rk.github.io"
breadcrumbs              : true # true, false (default)
words_per_minute         : 200

atom_feed:
  path                   : # blank (default) uses feed.xml
search                   : true #, false (default)
search_full_content      : true #, false (default)
search_provider          : lunr # lunr (default), algolia, google
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true

category-list: [oscp, htb, ctf, misc]
# Social Sharing
twitter:
  username               : m4nd4rk
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
  

# Site Author
author:
  name             : "Abhijeet"
  avatar           : "/assets/images/avatar.png" # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "Infosec Student, OSCP"
  location         : "USA"
  email            :
  links:
    #- label: "Email"
    #  icon: "fas fa-fw fa-envelope-square"
    #  url: mailto:butter0verflow@gmail.com
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/butter0verflow"
    #- label: "Facebook"
    #  icon: "fab fa-fw fa-facebook-square"
      # url: "https://facebook.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/butter0verflow"
    #- label: "Website"
    #  icon: "fas fa-fw fa-link"
    #  url: "https://butter0verflow.github.io"
    #- label: "Instagram"
    #  icon: "fab fa-fw fa-instagram"
      # url: 

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/butter0verflow"
    #- label: "Facebook"
    #  icon: "fab fa-fw fa-facebook-square"
    #  url: "https://facebook.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/butter0verflow"

